### ISSUE TITLE
Autodetect CONDOR_OS in the manual_glidein_submit tool

### ISSUE THREAD

**Issue by mmascher** [glideinWMS/glideinwms#449]
**Describe the bug**
By default `CONDOR_OS` is set to `default`  in the [manual_glidein_submit](https://github.com/glideinWMS/glideinwms/blob/70947708fccc8a0814786a43c96553c125652479/factory/tools/manual_glidein_submit.py#L227) script. However this causes failures in the `condor_master` startup when worker nodes are Rocky9 for example. The rhel8 condor tarball are used by defualt and causing:

```
error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

We should use automatic detection of the CONDOR_OS.

**Info (please complete the following information):**
-   Priority: high
-   Stakeholders: CMS
-   Components: factory

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modify manual_glidein_submit.py to use automatic detection of CONDOR_OS instead of the default value. This will prevent failures in condor_master startup on newer OS versions like Rocky9.

I also created pull request: https://github.com/glideinWMS/glideinwms/pull/450


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
