### ISSUE TITLE
Glidein statistics collection fails in HTCondor 8.9.13 and later

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#59]
It appears the statistics collection depends on the existence of the file `${main_starter_log}` which defaults to a file named `log/StarterLog`.

This file is no longer created starting in 8.9.13.

**Comment by mambelli** [comment]
Hi Brian,
from the StarterLog we collect info like how many jobs started, completed, if they ended w/ exit code 0, not 0 or because of a signal.
Is there a better way to get this?

Asking in HTCondor-users it seems that the StarterLog and StarterLog.slot* files are still created (we look for both patterns). Maybe the file was missing, maybe something went wrong in the parsing.
Could you provide some more info, e.g. the Glidein logs that caused the problem? or a recipe to reproduce the problem?

Thank you,
Marco

**Comment by bbockelm** [comment]
Hi Marco,

In the condor users response you got, @GregThain said that `StarterLog` (no suffix) is no longer created.  Since the stats collection is inside a conditional that tests for that file's existence, there are no statistics printed.  You can reproduce by running a glidein with any 9.x.y release.

I added a frontend script to create an empty file in that location and the statistics collection started working again.

Brian

**Comment by mambelli** [comment]
Fixed considering the existence of any starter log:
- StarterLog: `${main_starter_log}`
- Slot logs: `slotlogs=$(ls -1 ${main_starter_log}.slot* 2>/dev/null)`
