### ISSUE TITLE
Add attribute for singularity variant

### ISSUE THREAD

**Issue by matyasselmeci** [glideinWMS/glideinwms#63]
Now that there are multiple forks of Singularity (e.g. AppTainer, Singularity CE), in addition to `SINGULARITY_VERSION`, it would be useful to add the variant as an attribute (suggested name: `SINGULARITY_VARIANT`). According to @DrDaveD, this is the first word of the output of `singularity --version`, for example
```
singulary-ce version 3.9.0-rc.3
```
should result in `SINGULARITY_VARIANT="singularity-ce"`.

This is especially important since AppTainer plans to reset their version to 1.0.0 and start numbering from there.

**Comment by mambelli** [comment]
@matyasselmeci  Have a counter-proposal
What about `SINGULARITY_FULL_VERSION`, containing the whole string returned by `singularity --version`
Or, even better `CONTAINERSW_FULL_VERSION`, since it is not only singularity. It is also apptainer, soon maybe also podman.

In short, my preference would be:
1. CONTAINERSW_FULL_VERSION containing the whole version string
2. SINGULARITY_FULL_VERSION containing the whole version string (if 1 is not OK)

**Comment by matyasselmeci** [comment]
I'm OK with using the whole version string. The issue with CONTAINERSW_FULL_VERSION though is what if you have multiple runtimes installed, e.g. both singularity and podman - which one would you report?

**Comment by mambelli** [comment]
The only one used by the glidein. 
Currently it is a flavor of singularity, the first one encountered in the search places, with preference for apptainer, then singularity, then singularity-pro (singularity-ce). 
GlideinWMS is advertising also:
``` 
CONTAINERSW_PATH
CONTAINERSW_VERSION
CONTAINERSW_FULL_VERSION
CONTAINERSW_MODE
```
For now, these are the same as the SINGULARITY_ variables. The idea is that in the future someone will require also the support of another container software and these variables will all point to the one that has to be used (as requested by the VO or the site). Probably a CONTAINERSW_NAME or CONTAINERWS_ID will have to be added to select different behaviors depending on the name of the container sw. I'd like the idea to start thinking along these ways because there is no guarantee that apptainer will not diverge in behavior from singularity

**Comment by mambelli** [comment]
Do you think in the future we'll have to advertise the availability and versions of multiple container software (all the ones that are installed and available)?
In this case, we may need a `SINGULARITY_FULL_VERSION`, `PODMAN_FULL_VERSION` and maybe also `APPTAINER_FULL_VERSION`.

**Comment by matyasselmeci** [comment]
What about a nested classad?
```
CONTAINERSW_VERSIONS = [ SINGULARITY="singularity-ce 3.5.5"; APPTAINER="apptainer 1.0"; PODMAN="4.1.0"; ]
```

**Comment by matyasselmeci** [comment]
I think I'm fine with only reporting the one glideinwms will use by "default", though. @rynge , @bbockelm , what do you think?

**Comment by rynge** [comment]
Yes, I think this is part of a larger discussion about what takes precedence and would we ever support more than one at the same time? If it is one and one only, just reporting that version is fine.

**Comment by mambelli** [comment]
GlideinWMS as of 3.9.5 will look in the following places for the following binaries:
```
    # 1. Optional: Look first in the override path (GLIDEIN_SINGULARITY_BINARY_OVERRIDE)
    # 2. Look for 'apptainer' and then 'singularity' in the path suggested via $1 (SINGULARITY_BIN)
    #      (keywords: PATH -> go to step 3 - ie start w/ $PATH;
    #           OSG -> OSG location, and continue from step 3 if failed, this is the default)
    # 3. Look in $PATH for 'apptainer' and then 'singularity'
    # 4. Invoke module singularitypro
    # 5. Invoke module singularity
    # 6. Look in the default OSG location 
    #   (OSG_SINGULARITY_BINARY_DEFAULT="/cvmfs/oasis.opensciencegrid.org/mis/singularity/bin/singularity")
```
The first one found that passes all the tests is the one used to populate the SINGULARITY_ and CONTAINERSW_ variables. 
The binary, whichever it is, it is supposed to behave like singularity (there are some compensations for differences found in different versions).

In the future probably will be desirable to support multiple container softwares with different behaviors.
When that happens I'm expecting a preference-ordered list with all the acceptable binaries.
I'm not sure if it will have to be the pilot job to discover and adverise all the available container sowtwares and if it is, defining ad hoc variables for each container software probably is not ideal.

**Comment by mambelli** [comment]
The variable to use is CONTAINERSW_FULL_VERSION
GWMS is advertising also SINGULARITY_FULL_VERSION with the same content, but we'd prefer users to move to the new naming.
